### ISSUE TITLE
Packages version aren't not fixed

### ISSUE THREAD

**Issue by fabriciofx** [viniciussoaresti/pantrie#32]
In `packages.json` file we can see something like this:
```
"@angular/forms": "~8.2.14",
"@angular/platform-browser": "~8.2.14",
"@angular/platform-browser-dynamic": "~8.2.14",
"@angular/router": "~8.2.14",
"rxjs": "~6.4.0",
"tslib": "^1.10.0",
```
As you can see, the packages version aren't fasten (usage of `^` and `~`) and it can lead to errors because two developers are using different package versions. So, my suggestion is to fasten the version of the packages.

**Comment by viniciussoaresti** [comment]
@fabriciofx Will do!

**Comment by viniciussoaresti** [comment]
@fabriciofx does it mean using ^ on all packages? I'm giving it a quick read [here](https://michaelsoolee.com/npm-package-tilde-caret/) and it's what I'm guessing.

**Comment by viniciussoaresti** [comment]
Judging by the [npm documentation](https://docs.npmjs.com/files/package.json) I think it's the best option.

**Comment by viniciussoaresti** [comment]
Build passing, problem solved. Closing the issue, reopening if needed, after @fabriciofx 's feedback.

**Comment by fabriciofx** [comment]
@viniciussoaresti Noooooo! Dude, you're completely wrong! Please, read the documentation again! According with *The Internet* a.k.a *Google* the correct solution fo this problem is the `npm shrinkwrap` command. But IMHO, I don't like this solution so much. So, I think the better solution is **remove** all `^` and `~` characters which are front of versions numbers.

**Comment by viniciussoaresti** [comment]
@fabriciofx hmm... interesting...
Okay, following your lead, reopening the issue and removing the '^' and '~' characters.

**Comment by viniciussoaresti** [comment]
Solved on pr #35.

**Comment by fabriciofx** [comment]
@viniciussoaresti don't use *solve* or *solved* in this context. Prefer *fix* or *fixed*.

**Comment by viniciussoaresti** [comment]
@fabriciofx Okay!
